"""Driver models and configuration parsing for bempp_audio."""

from bempp_audio.driver.generic25 import (
    Generic25DriverConfig,
    Generic25EnclosureConfig,
    Generic25DuctConfig,
    Generic25WaveguideConfig,
    Generic25SystemConfig,
    generic25_to_compression_driver_config,
    load_generic25,
    parse_generic25,
)
from bempp_audio.driver.compression_config import (
    CompressionDriverConfig,
    DriverElectroMechConfig,
    VoiceCoilImpedanceModel,
    FrequencyWeighting,
    RearVolumeConfig,
    FrontDuctConfig,
    PhasePlugConfig,
    ExitConeConfig,
    FrontRadiationMode,
    WaveguideMatrixMethod,
)
from bempp_audio.driver.network import (
    AcousticMedium,
    AcousticNodeResult,
    CompressionDriverExcitation,
    CompressionDriverNetwork,
    CompressionDriverNetworkOptions,
    compute_blocked_electrical_impedance,
    compute_mechanical_impedance,
    solve_two_node_acoustic_network,
    conical_waveguide_y_matrix,
    conical_waveguide_abcd_matrix,
)
from bempp_audio.driver.validation import (
    plane_wave_tube_load_impedance,
    vacuum_electrical_impedance,
    fit_vacuum_electro_mech,
)
from bempp_audio.driver.fitting import (
    ParameterSpec,
    FitDiagnostics,
    FitResult,
    fit_vacuum_impedance,
    fit_network_impedance,
    fit_acoustic_from_tube_impedance,
    apply_vacuum_fit_to_config,
)

__all__ = [
    "Generic25DriverConfig",
    "Generic25EnclosureConfig",
    "Generic25DuctConfig",
    "Generic25WaveguideConfig",
    "Generic25SystemConfig",
    "generic25_to_compression_driver_config",
    "load_generic25",
    "parse_generic25",
    "CompressionDriverConfig",
    "DriverElectroMechConfig",
    "VoiceCoilImpedanceModel",
    "FrequencyWeighting",
    "RearVolumeConfig",
    "FrontDuctConfig",
    "PhasePlugConfig",
    "ExitConeConfig",
    "FrontRadiationMode",
    "WaveguideMatrixMethod",
    "AcousticMedium",
    "AcousticNodeResult",
    "CompressionDriverExcitation",
    "CompressionDriverNetwork",
    "CompressionDriverNetworkOptions",
    "compute_blocked_electrical_impedance",
    "compute_mechanical_impedance",
    "solve_two_node_acoustic_network",
    "conical_waveguide_y_matrix",
    "conical_waveguide_abcd_matrix",
    "plane_wave_tube_load_impedance",
    "vacuum_electrical_impedance",
    "fit_vacuum_electro_mech",
    "ParameterSpec",
    "FitDiagnostics",
    "FitResult",
    "fit_vacuum_impedance",
    "fit_network_impedance",
    "fit_acoustic_from_tube_impedance",
    "apply_vacuum_fit_to_config",
]
